import { Command } from 'commander';
import { helpConfig } from '../../lib/help.ts';
import { runCommand, runDestroy } from './_shared.ts';

export const form = new Command('form')
	.description('destroy a form generated by `vela generate form`')
	.argument('<model>', 'model name used when the form was generated (e.g., contact, login)')
	.option('-y, --yes', 'skip confirmation prompt')
	.option(
		'--route <route>',
		'custom route the form was generated at (must match the --route used at generation)'
	)
	.allowUnknownOption(true)
	.configureHelp(helpConfig)
	.action((model: string, opts: { yes?: boolean; route?: string }) =>
		runCommand(
			() =>
				runDestroy(
					'destroy-form',
					model,
					`Destroy form "${model}"? Removes the route directory and the schema file.`,
					{
						summary: `Destroyed form "${model}".`,
						task: {
							title: `Destroying form "${model}"`,
							success: `Destroyed form "${model}"`,
							error: `Failed to destroy form "${model}"`
						}
					},
					opts
				),
			'Failed to destroy form.'
		)
	);
