import { Command } from 'commander';
import { helpConfig } from '../../lib/help.ts';
import { runCommand, runDestroy } from './_shared.ts';

export const resource = new Command('resource')
	.description('destroy a resource generated by `vela generate resource`')
	.argument('<model>', 'model path used when the resource was generated (e.g., contacts, articles)')
	.option('-y, --yes', 'skip confirmation prompt')
	.allowUnknownOption(true)
	.configureHelp(helpConfig)
	.action((model: string, opts) =>
		runCommand(
			() =>
				runDestroy(
					'destroy-resource',
					model,
					`Destroy resource "${model}"? Drops the collection and removes the schema file.`,
					{
						summary: `Destroyed resource "${model}".`,
						task: {
							title: `Destroying resource "${model}"`,
							success: `Destroyed resource "${model}"`,
							error: `Failed to destroy resource "${model}"`
						}
					},
					opts
				),
			'Failed to destroy resource.'
		)
	);
