import { Command } from 'commander';
import { helpConfig } from '../../lib/help.ts';
import { runCommand, runDestroy } from './_shared.ts';

export const scaffold = new Command('scaffold')
	.description('destroy a scaffold generated by `vela generate scaffold`')
	.argument('<model>', 'model name used when the scaffold was generated (e.g., contact, todo)')
	.option('-y, --yes', 'skip confirmation prompt')
	.option(
		'--route <route>',
		'custom route the scaffold was generated at (must match the --route used at generation)'
	)
	.allowUnknownOption(true)
	.configureHelp(helpConfig)
	.action((model: string, opts: { yes?: boolean; route?: string }) =>
		runCommand(
			() =>
				runDestroy(
					'destroy-scaffold',
					model,
					`Destroy scaffold "${model}"? Removes the route directory, schema file, and drops the collection. Shadcn components are retained.`,
					{
						summary: `Destroyed scaffold "${model}".`,
						nextSteps: [
							'Shadcn components added during scaffolding are preserved — remove them manually if nothing else uses them.'
						],
						task: {
							title: `Destroying scaffold "${model}"`,
							success: `Destroyed scaffold "${model}"`,
							error: `Failed to destroy scaffold "${model}"`
						}
					},
					opts
				),
			'Failed to destroy scaffold.'
		)
	);
