import { Command } from 'commander';
import { helpConfig } from '../../lib/help.ts';
import { runCommand, runDestroy } from './_shared.ts';

export const schema = new Command('schema')
	.description('destroy a zod schema generated by `vela generate schema`')
	.argument('<model>', 'schema model name (e.g., contact, login)')
	.option('-y, --yes', 'skip confirmation prompt')
	.allowUnknownOption(true)
	.configureHelp(helpConfig)
	.action((model: string, opts) =>
		runCommand(
			() =>
				runDestroy(
					'destroy-schema',
					model,
					`Destroy schema "${model}"? Removes the zod schema file.`,
					{
						summary: `Destroyed schema "${model}".`,
						task: {
							title: `Destroying schema "${model}"`,
							success: `Destroyed schema "${model}"`,
							error: `Failed to destroy schema "${model}"`
						}
					},
					opts
				),
			'Failed to destroy schema.'
		)
	);
